language: java
jdk:
- openjdk11
addons:
  sonarcloud:
    organization: jhaloyn
    token: c63141d084148304a2b7ab9994cdb99123194f26

script:
- mvn test -DfailIfNoTests=false -Dmaven.test.failure.ignore=true -Dtest=BookKeeperAdminTest sonar:sonar -Dsonar.projectKey=Jhaloyn_bookkeeper



